conduit:
  application:
    cors:
      allowOrigin: "*"
      allowHeaders:
        - Content-Type
        - Authorization
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
