name: isr_dart24
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  conduit: ^4.3.7
  conduit_core: ^4.3.6
  conduit_postgresql: ^4.4.0
  postgres: ^2.6.4
  conduit_common: ^4.4.0
  mysql1: ^0.19.2
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.6
